name: Docker Image CI and publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  env:
    METASHAPE_VER: 1_7_5
    METASHAPE_WHEEL: Metashape-1.7.5-cp35.cp36.cp37.cp38-abi3-linux_x86_64.whl

  push_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ASDC_PACKAGES }}

      - name: Push metashape image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          build-args: METASHAPE_VER=$METASHAPE_VER, METASHAPE_WHEEL=$METASHAPE_WHEEL
          tags: ghcr.io/auscalabledronecloud/metashape:latest
          push: true

      - name: Push metashape-server imge to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          build-args: METASHAPE_VER=$METASHAPE_VER
          tags: ghcr.io/auscalabledronecloud/metashape-server:latest
          push: true

      - name: Push metashape-license-server image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.license
          tags: ghcr.io/auscalabledronecloud/metashape-license-server:latest
          push: true
